eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
        defaultZone: http://localhost:8761/eureka/
    #  defaultZone: http://localhost:8080/eureka/
  instance:
    hostname: localhost
